const test=require('node:test');const assert=require('node:assert/strict');const bcrypt=require('bcryptjs');
const { esBasePruebasAislada } = require('../lib/testDatabase');
if(process.env.NODE_ENV!=='test'||process.env.TEST_DATABASE!=='true'||!esBasePruebasAislada(process.env.DB_NAME))throw new Error('Entorno de integración inseguro');
const db=require('../db/conexion');const{app}=require('../index');
const password='AdminTest-123';let server,base,token,clienteId,productoId;
async function request(path,{method='GET',body,headers={}}={}){const r=await fetch(base+path,{method,headers:{...(body?{'Content-Type':'application/json'}:{}),...(token?{Authorization:`Bearer ${token}`}:{}) ,...headers},body:body?JSON.stringify(body):undefined});const type=r.headers.get('content-type')||'',data=type.includes('json')?await r.json():await r.text();return{status:r.status,data,headers:r.headers};}
test.before(async()=>{await db.promise.query('DELETE FROM pago_formas_pago');await db.promise.query('DELETE FROM venta_formas_pago')});
test.before(async()=>{const tablas=['intentos_login','sesiones_usuario','auditoria_operaciones','auditoria_respaldos','historial_traslados','control_instancia_pos','aplicaciones_pago','movimientos_cartera','pagos','cuentas_por_cobrar','detalle_orden_venta','ordenes_venta','detalle_venta','ventas','pagos_proveedores','cuentas_por_pagar_proveedores','detalle_compra','compras','movimientos_inventario','producto_proveedores','productos','proveedores','clientes','autorizaciones_admin','usuarios','configuracion_negocio'];for(const t of tablas)await db.promise.query(`DELETE FROM \`${t}\``);const hash=await bcrypt.hash(password,4);await db.promise.query("INSERT INTO usuarios(nombre,username,password_hash,password,rol,activo) VALUES('Administrador Prueba','admin_test',?,NULL,'ADMON_GRAL',1)",[hash]);await db.promise.query("INSERT INTO clientes(nombre_razon_social,permite_credito,activo) VALUES('Público General',0,1),('Cliente Integración',1,1)");const[[cliente]]=await db.promise.query("SELECT id FROM clientes WHERE nombre_razon_social='Cliente Integración'");clienteId=cliente.id;await db.promise.query('INSERT INTO configuracion_negocio(id,nombre_comercial) VALUES(1,\'POS Prueba\')');await new Promise(resolve=>{server=app.listen(0,'127.0.0.1',resolve)});base=`http://127.0.0.1:${server.address().port}`;});
test.after(async()=>{if(server)await new Promise(resolve=>server.close(resolve));await db.promise.end();});
test('recorrido transaccional HTTP completo',async()=>{
  let r=await request('/auth/login',{method:'POST',body:{username:'admin_test',password}});assert.equal(r.status,200);token=r.data.token;
  r=await request('/auth/me');assert.equal(r.status,200);assert.equal(r.data.usuario.rol,'ADMON_GRAL');
  const tokenRevocado=token;r=await request('/auth/logout',{method:'POST'});assert.equal(r.status,200);
  await new Promise(resolve=>server.close(resolve));await new Promise(resolve=>{server=app.listen(0,'127.0.0.1',resolve)});base=`http://127.0.0.1:${server.address().port}`;
  token=tokenRevocado;r=await request('/auth/me');assert.equal(r.status,401);
  token=null;r=await request('/auth/login',{method:'POST',body:{username:'admin_test',password}});assert.equal(r.status,200);token=r.data.token;const tokenAdmin=token;
  const passwordCajero='x';r=await request('/usuarios',{method:'POST',body:{nombre:'Cajero Prueba',username:'cajero_test',password:passwordCajero,rol:'CAJERO'}});assert.equal(r.status,201);
  r=await request('/auth/login',{method:'POST',body:{username:'cajero_test',password:passwordCajero}});assert.equal(r.status,200);token=r.data.token;
  r=await request('/proveedores');assert.equal(r.status,200);
  r=await request('/ventas');assert.equal(r.status,200);
  r=await request('/cuentas-proveedores');assert.equal(r.status,403);
  r=await request('/proveedores',{method:'POST',body:{nombre:'No permitido'}});assert.equal(r.status,403);
  r=await request('/compras',{method:'POST',headers:{'Idempotency-Key':'cajero-no-permitido'},body:{proveedor_id:1,productos:[{producto_id:1,cantidad:1,costo:1}]}});assert.equal(r.status,403);
  token=tokenAdmin;
  r=await request('/usuarios');assert.equal(r.status,200);const cajero=r.data.find(x=>x.username==='cajero_test');assert.ok(cajero);
  const passwordEditada='y';r=await request(`/usuarios/${cajero.id}`,{method:'PUT',body:{nombre:'Cajero Prueba Editado',username:'cajero_test',password:passwordEditada,rol:'CAJERO'}});assert.equal(r.status,200);
  r=await request('/auth/login',{method:'POST',body:{username:'cajero_test',password:passwordEditada}});assert.equal(r.status,200);token=tokenAdmin;
  r=await request('/proveedores',{method:'POST',body:{nombre:'Proveedor Prueba',rfc:'TST010101AA1'}});assert.equal(r.status,201);const proveedorId=r.data.id;
  r=await request('/proveedores',{method:'POST',body:{nombre:'  Proveedor   Prueba  '}});assert.equal(r.status,409);
  r=await request('/proveedores?buscar=Prueba&estado=TODOS');assert.equal(r.status,200);assert.ok(r.data.some(x=>x.id===proveedorId));
  r=await request(`/proveedores/${proveedorId}`,{method:'PUT',body:{nombre:'Proveedor Prueba',razon_social:'Proveedor de Integración SA',rfc:'TST010101AA1',notas:'Entrega semanal'}});assert.equal(r.status,200);
  r=await request('/productos',{method:'POST',body:{codigo:'TEST-KG',nombre:'Aguacate prueba',precio_venta:50,costo:30,unidad:'KG',stock_minimo:2,proveedor_id:proveedorId}});assert.equal(r.status,201);productoId=r.data.id;
  const movimientoKey='movimiento-integracion-0001',movimiento={producto_id:productoId,tipo:'ENTRADA',cantidad:10,motivo:'Carga de integración',idempotency_key:movimientoKey};
  r=await request('/inventario/movimiento',{method:'POST',headers:{'Idempotency-Key':movimientoKey},body:movimiento});assert.equal(r.status,201);assert.equal(Number(r.data.stock),10);
  r=await request('/inventario/movimiento',{method:'POST',headers:{'Idempotency-Key':movimientoKey},body:movimiento});assert.equal(r.status,200);assert.equal(r.data.repetido,true);assert.equal(Number(r.data.stock),10);
  const[productoMovimientoConcurrente]=await db.promise.query("INSERT INTO productos(codigo,nombre,precio_venta,costo,unidad,stock,stock_minimo,activo) VALUES('MOV-CONCURRENT','Movimiento concurrente',10,5,'KG',10,0,1)");
  const movimientosIguales=await Promise.all(['movimiento-concurrente-01','movimiento-concurrente-02'].map(key=>request('/inventario/movimiento',{method:'POST',headers:{'Idempotency-Key':key},body:{producto_id:productoMovimientoConcurrente.insertId,tipo:'ENTRADA',cantidad:1,motivo:'Entradas simultáneas',idempotency_key:key}})));
  assert.ok(movimientosIguales.every(x=>x.status===201),JSON.stringify(movimientosIguales));assert.equal(Number((await db.promise.query('SELECT stock FROM productos WHERE id=?',[productoMovimientoConcurrente.insertId]))[0][0].stock),12);
  const compraKey='compra-integracion-0001',compra={proveedor_id:proveedorId,folio:'COMP-TEST-1',idempotency_key:compraKey,productos:[{producto_id:productoId,cantidad:2,costo:31}]};
  r=await request('/compras',{method:'POST',headers:{'Idempotency-Key':compraKey},body:compra});assert.equal(r.status,201);const compraId=r.data.id;
  const[[relacionProveedor]]=await db.promise.query('SELECT costo_ultimo,activo FROM producto_proveedores WHERE producto_id=? AND proveedor_id=?',[productoId,proveedorId]);assert.equal(Number(relacionProveedor.costo_ultimo),31);assert.equal(Number(relacionProveedor.activo),1);
  r=await request(`/proveedores/${proveedorId}`);assert.equal(r.status,200);assert.ok(r.data.productos.some(x=>x.id===productoId));assert.ok(Number(r.data.proveedor.total_comprado)>0);
  r=await request('/compras',{method:'POST',headers:{'Idempotency-Key':compraKey},body:compra});assert.equal(r.status,200);assert.equal(r.data.id,compraId);assert.equal(r.data.repetida,true);
  r=await request('/compras',{method:'POST',headers:{'Idempotency-Key':'compra-producto-repetido'},body:{...compra,idempotency_key:'compra-producto-repetido',folio:'COMP-TEST-DUP',productos:[...compra.productos,...compra.productos]}});assert.equal(r.status,400);
  r=await request(`/proveedores/${proveedorId}/estado`,{method:'PATCH',body:{activo:false}});assert.equal(r.status,200);
  r=await request('/compras',{method:'POST',headers:{'Idempotency-Key':'compra-proveedor-inactivo'},body:{...compra,idempotency_key:'compra-proveedor-inactivo',folio:'COMP-TEST-INACTIVO'}});assert.equal(r.status,409);
  r=await request(`/proveedores/${proveedorId}/estado`,{method:'PATCH',body:{activo:true}});assert.equal(r.status,200);
  r=await request(`/compras/${compraId}/cancelar`,{method:'POST',body:{motivo:'Cancelación de integración'}});assert.equal(r.status,200);
  const compraPagoKey='compra-pago-proveedor-0002';r=await request('/compras',{method:'POST',headers:{'Idempotency-Key':compraPagoKey},body:{proveedor_id:proveedorId,folio:'COMP-PAGO-2',idempotency_key:compraPagoKey,productos:[{producto_id:productoId,cantidad:1,costo:20}]}});assert.equal(r.status,201);const compraPagoId=r.data.id;
  const[[cuentaProveedor]]=await db.promise.query('SELECT id,saldo_pendiente FROM cuentas_por_pagar_proveedores WHERE compra_id=?',[compraPagoId]);assert.equal(Number(cuentaProveedor.saldo_pendiente),20);
  const pagoProveedorKey='pago-proveedor-integracion-0001',pagoProveedorBody={cuenta_id:cuentaProveedor.id,monto:5,metodo_pago:'TRANSFERENCIA',referencia:'PAGO-PROV-1',idempotency_key:pagoProveedorKey};
  r=await request('/cuentas-proveedores/pagos',{method:'POST',headers:{'Idempotency-Key':pagoProveedorKey},body:pagoProveedorBody});assert.equal(r.status,201);assert.equal(Number(r.data.saldo_pendiente),15);
  r=await request('/cuentas-proveedores/pagos',{method:'POST',headers:{'Idempotency-Key':pagoProveedorKey},body:pagoProveedorBody});assert.equal(r.status,200);assert.equal(r.data.repetido,true);
  r=await request('/cuentas-proveedores');assert.equal(r.status,200);assert.equal(Number(r.data.deuda_total),15);
  r=await request(`/proveedores/${proveedorId}`);assert.equal(r.status,200);assert.equal(r.data.pagos.length,1);assert.ok(r.data.movimientos.some(m=>m.tipo==='PAGO'&&Number(m.abono)===5));assert.equal(Number(r.data.proveedor.deuda_pendiente),15);
  const ventaKey='venta-integracion-0001',venta={cliente_id:clienteId,tipo_pago:'CONTADO',metodos_pago:[{metodo_pago:'EFECTIVO',monto:30},{metodo_pago:'TRANSFERENCIA',monto:64,referencia:'TEST-REF'}],idempotency_key:ventaKey,productos:[{producto_id:productoId,cantidad:2,precio_unitario:47}]};
  r=await request('/ventas/crear',{method:'POST',headers:{'Idempotency-Key':ventaKey},body:venta});assert.equal(r.status,201);assert.equal(Number(r.data.total),94);const ventaContado=r.data.venta_id;
  const[[detallePrecio]]=await db.promise.query('SELECT precio_unitario FROM detalle_venta WHERE venta_id=?',[ventaContado]);assert.equal(Number(detallePrecio.precio_unitario),47);
  const[formasVenta]=await db.promise.query('SELECT metodo_pago,monto FROM venta_formas_pago WHERE venta_id=? ORDER BY id',[ventaContado]);assert.equal(formasVenta.length,2);assert.equal(formasVenta.reduce((s,x)=>s+Number(x.monto),0),94);
  r=await request('/ventas/crear',{method:'POST',headers:{'Idempotency-Key':ventaKey},body:venta});assert.equal(r.status,200);assert.equal(r.data.venta_id,ventaContado);assert.equal(r.data.repetida,true);
  r=await request(`/ventas/${ventaContado}/ticket-url`,{method:'POST'});assert.equal(r.status,200);const ticket=await fetch(base+r.data.url);assert.equal(ticket.status,200);assert.match(await ticket.text(),/ORIGINAL/);
  const creditoKey='venta-integracion-0002';r=await request('/ventas/crear',{method:'POST',headers:{'Idempotency-Key':creditoKey},body:{...venta,idempotency_key:creditoKey,tipo_pago:'CREDITO',metodo_pago:null,referencia_pago:null,productos:[{producto_id:productoId,cantidad:1,precio_unitario:48}]}});assert.equal(r.status,201);const ventaCredito=r.data.venta_id;
  const[[creditoSinMetodo]]=await db.promise.query('SELECT metodo_pago,referencia_pago,total FROM ventas WHERE id=?',[ventaCredito]);assert.equal(creditoSinMetodo.metodo_pago,null);assert.equal(creditoSinMetodo.referencia_pago,null);assert.equal(Number(creditoSinMetodo.total),48);
  const[[cuenta]]=await db.promise.query('SELECT id,saldo_pendiente FROM cuentas_por_cobrar WHERE venta_id=?',[ventaCredito]);
  const pagoClienteKey='pago-cliente-integracion-0001',pagoClienteBody={cliente_id:clienteId,monto_recibido:10,cuenta_ids:[cuenta.id],modo:'MANUAL',aplicaciones:[{cuenta_id:cuenta.id,monto:10}],metodos_pago:[{metodo_pago:'EFECTIVO',monto:4},{metodo_pago:'CHEQUE',monto:6,referencia:'CHK-MIXTO'}],idempotency_key:pagoClienteKey};
  r=await request('/cuentas/pagos',{method:'POST',headers:{'Idempotency-Key':pagoClienteKey},body:pagoClienteBody});assert.equal(r.status,201);assert.equal(r.data.metodo_pago,'MIXTO');const pagoId=r.data.pago_id;
  r=await request('/cuentas/pagos',{method:'POST',headers:{'Idempotency-Key':pagoClienteKey},body:pagoClienteBody});assert.equal(r.status,200);assert.equal(r.data.repetido,true);
  r=await request('/cuentas/pagos',{method:'POST',headers:{'Idempotency-Key':'pago-cliente-integracion-exceso'},body:{cliente_id:clienteId,monto_recibido:9999,cuenta_ids:[cuenta.id],modo:'MANUAL',aplicaciones:[{cuenta_id:cuenta.id,monto:9999}],metodo_pago:'EFECTIVO',idempotency_key:'pago-cliente-integracion-exceso'}});assert.equal(r.status,409);
  r=await request(`/cuentas/pagos/${pagoId}/cancelar`,{method:'POST',body:{motivo:'Reversión de prueba',password_admin:password}});assert.equal(r.status,200);
  r=await request(`/ventas/${ventaCredito}/cancelar`,{method:'POST',body:{motivo:'Cancelación de prueba',password_admin:password}});assert.equal(r.status,200);
  r=await request('/stats');assert.equal(r.status,200);assert.ok('ingresos_mes'in r.data);
  r=await request('/chatbot',{method:'POST',body:{pregunta:'cuánto vendí hoy'}});assert.equal(r.status,200);assert.equal(r.data.soportada,true);
  r=await request('/prediccion');assert.equal(r.status,200);assert.ok(Array.isArray(r.data.predicciones));
  r=await request('/ordenes',{method:'POST',body:{cliente_id:clienteId,estado:'PENDIENTE',observaciones:'Orden integración',productos:[{producto_id:productoId,cantidad:1,precio_unitario:45}]}});assert.equal(r.status,201);const ordenId=r.data.orden_id;
  r=await request(`/ordenes/${ordenId}/convertir`,{method:'POST',body:{tipo_pago:'CONTADO',metodo_pago:'CHEQUE',referencia_pago:'CHK-TEST'}});assert.equal(r.status,201);
  const[[precioOrdenConvertida]]=await db.promise.query('SELECT precio_unitario FROM detalle_venta WHERE venta_id=?',[r.data.venta_id]);assert.equal(Number(precioOrdenConvertida.precio_unitario),45);
  r=await request(`/ordenes/${ordenId}/convertir`,{method:'POST',body:{tipo_pago:'CONTADO',metodo_pago:'CHEQUE',referencia_pago:'CHK-TEST'}});assert.equal(r.status,409);
  r=await request('/configuracion',{method:'PUT',body:{nombre_comercial:'POS Integración',moneda:'MXN',papel_mm:58,ticket_escala_texto:80,ticket_margen_mm:1,ticket_mostrar_logo:false,ticket_logo_alto_contraste:true,ticket_logo_ancho_pct:40,stock_minimo_default:1,vencimiento_dias:30}});assert.equal(r.status,200);
  r=await request(`/ventas/${ventaContado}/ticket-url`,{method:'POST'});assert.equal(r.status,200);const ticketConfigurado=await fetch(base+r.data.url);const htmlTicketConfigurado=await ticketConfigurado.text();assert.match(htmlTicketConfigurado,/@page\{size:58mm auto;margin:1mm\}/);assert.match(htmlTicketConfigurado,/font-size:80%/);assert.doesNotMatch(htmlTicketConfigurado,/class="logo-ticket"/);
  r=await request('/reportes/ventas.csv');assert.equal(r.status,200);assert.match(r.data,/folio/);
  const[[onlyAdmin]]=await db.promise.query("SELECT id FROM usuarios WHERE username='admin_test'");r=await request(`/usuarios/${onlyAdmin.id}`,{method:'PUT',body:{nombre:'Administrador Prueba',username:'admin_test',rol:'CAJERO'}});assert.equal(r.status,409);
  const[[stock]]=await db.promise.query('SELECT stock FROM productos WHERE id=?',[productoId]);assert.equal(Number(stock.stock),8);
  const[[duplicadas]]=await db.promise.query('SELECT COUNT(*) total FROM ventas WHERE idempotency_key=?',[ventaKey]);assert.equal(Number(duplicadas.total),1);
  const[productoConcurrente]=await db.promise.query("INSERT INTO productos(codigo,nombre,precio_venta,costo,unidad,stock,stock_minimo,activo) VALUES('CONCURRENT-1','Producto concurrente',10,5,'KG',10,0,1)");
  const ventaConcurrente=(key)=>request('/ventas/crear',{method:'POST',headers:{'Idempotency-Key':key},body:{cliente_id:clienteId,tipo_pago:'CONTADO',metodo_pago:'EFECTIVO',idempotency_key:key,productos:[{producto_id:productoConcurrente.insertId,cantidad:7,precio_unitario:10}]}});
  const concurrentes=await Promise.all([ventaConcurrente('venta-concurrente-caja-1'),ventaConcurrente('venta-concurrente-caja-2')]);
  assert.deepEqual(concurrentes.map(x=>x.status).sort(),[201,409]);
  const[[stockConcurrente]]=await db.promise.query('SELECT stock FROM productos WHERE id=?',[productoConcurrente.insertId]);assert.equal(Number(stockConcurrente.stock),3);
  const[[ventasConcurrentes]]=await db.promise.query("SELECT COUNT(*) total FROM ventas WHERE idempotency_key IN ('venta-concurrente-caja-1','venta-concurrente-caja-2')");assert.equal(Number(ventasConcurrentes.total),1);
  const[productoDuplicado]=await db.promise.query("INSERT INTO productos(codigo,nombre,precio_venta,costo,unidad,stock,stock_minimo,activo) VALUES('DUPLICATE-1','Producto duplicado',10,5,'KG',10,0,1)");
  const mismaKey='venta-simultanea-misma-key',mismaOperacion=()=>request('/ventas/crear',{method:'POST',headers:{'Idempotency-Key':mismaKey},body:{cliente_id:clienteId,tipo_pago:'CONTADO',metodo_pago:'EFECTIVO',idempotency_key:mismaKey,productos:[{producto_id:productoDuplicado.insertId,cantidad:2,precio_unitario:10}]}});
  const repetidas=await Promise.all([mismaOperacion(),mismaOperacion()]);assert.ok(repetidas.every(x=>[200,201].includes(x.status)));
  const[[stockDuplicado]]=await db.promise.query('SELECT stock FROM productos WHERE id=?',[productoDuplicado.insertId]);assert.equal(Number(stockDuplicado.stock),8);
  const[[unaVenta]]=await db.promise.query('SELECT COUNT(*) total FROM ventas WHERE idempotency_key=?',[mismaKey]);assert.equal(Number(unaVenta.total),1);
  const[productoRollback]=await db.promise.query("INSERT INTO productos(codigo,nombre,precio_venta,costo,unidad,stock,stock_minimo,activo) VALUES('ROLLBACK-1','Producto rollback',10,5,'KG',10,0,1)");
  await db.promise.query("CREATE TRIGGER test_fallo_detalle BEFORE INSERT ON detalle_venta FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Fallo inducido auditoria'");
  const antesRollback=await db.promise.query('SELECT COUNT(*) total FROM ventas').then(([rows])=>Number(rows[0].total));
  r=await request('/ventas/crear',{method:'POST',headers:{'Idempotency-Key':'venta-fallo-inducido'},body:{cliente_id:clienteId,tipo_pago:'CONTADO',metodo_pago:'EFECTIVO',idempotency_key:'venta-fallo-inducido',productos:[{producto_id:productoRollback.insertId,cantidad:2,precio_unitario:10}]}});assert.equal(r.status,500);
  await db.promise.query('DROP TRIGGER test_fallo_detalle');
  const despuesRollback=await db.promise.query('SELECT COUNT(*) total FROM ventas').then(([rows])=>Number(rows[0].total));assert.equal(despuesRollback,antesRollback);
  const[[stockRollback]]=await db.promise.query('SELECT stock FROM productos WHERE id=?',[productoRollback.insertId]);assert.equal(Number(stockRollback.stock),10);
  await db.promise.query("CREATE TRIGGER test_fallo_compra BEFORE INSERT ON detalle_compra FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Fallo compra inducido'");
  const comprasAntes=await db.promise.query('SELECT COUNT(*) total FROM compras').then(([rows])=>Number(rows[0].total));
  r=await request('/compras',{method:'POST',headers:{'Idempotency-Key':'compra-fallo-inducido'},body:{proveedor_id:proveedorId,folio:'COMP-FAIL',idempotency_key:'compra-fallo-inducido',productos:[{producto_id:productoRollback.insertId,cantidad:2,costo:5}]}});assert.equal(r.status,500);
  await db.promise.query('DROP TRIGGER test_fallo_compra');
  assert.equal(await db.promise.query('SELECT COUNT(*) total FROM compras').then(([rows])=>Number(rows[0].total)),comprasAntes);
  assert.equal(Number((await db.promise.query('SELECT stock FROM productos WHERE id=?',[productoRollback.insertId]))[0][0].stock),10);
  const creditoRollbackKey='venta-credito-rollback-pago';r=await request('/ventas/crear',{method:'POST',headers:{'Idempotency-Key':creditoRollbackKey},body:{cliente_id:clienteId,tipo_pago:'CREDITO',idempotency_key:creditoRollbackKey,productos:[{producto_id:productoRollback.insertId,cantidad:1,precio_unitario:10}]}});assert.equal(r.status,201);const ventaPagoRollback=r.data.venta_id;
  const[[cuentaPagoRollback]]=await db.promise.query('SELECT id,saldo_pendiente FROM cuentas_por_cobrar WHERE venta_id=?',[ventaPagoRollback]);
  await db.promise.query("CREATE TRIGGER test_fallo_pago BEFORE INSERT ON aplicaciones_pago FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Fallo pago inducido'");
  const pagosAntes=await db.promise.query('SELECT COUNT(*) total FROM pagos').then(([rows])=>Number(rows[0].total));
  r=await request('/cuentas/pagos',{method:'POST',headers:{'Idempotency-Key':'pago-fallo-inducido'},body:{cliente_id:clienteId,monto_recibido:5,cuenta_ids:[cuentaPagoRollback.id],modo:'MANUAL',aplicaciones:[{cuenta_id:cuentaPagoRollback.id,monto:5}],metodo_pago:'EFECTIVO',idempotency_key:'pago-fallo-inducido'}});assert.equal(r.status,500);
  await db.promise.query('DROP TRIGGER test_fallo_pago');
  assert.equal(await db.promise.query('SELECT COUNT(*) total FROM pagos').then(([rows])=>Number(rows[0].total)),pagosAntes);
  assert.equal(Number((await db.promise.query('SELECT saldo_pendiente FROM cuentas_por_cobrar WHERE id=?',[cuentaPagoRollback.id]))[0][0].saldo_pendiente),10);
  const pagoConcurrente=key=>request('/cuentas/pagos',{method:'POST',headers:{'Idempotency-Key':key},body:{cliente_id:clienteId,monto_recibido:7,cuenta_ids:[cuentaPagoRollback.id],modo:'MANUAL',aplicaciones:[{cuenta_id:cuentaPagoRollback.id,monto:7}],metodo_pago:'EFECTIVO',idempotency_key:key}});
  const pagosConcurrentes=await Promise.all([pagoConcurrente('pago-concurrente-1'),pagoConcurrente('pago-concurrente-2')]);assert.deepEqual(pagosConcurrentes.map(x=>x.status).sort(),[201,409]);
  assert.equal(Number((await db.promise.query('SELECT saldo_pendiente FROM cuentas_por_cobrar WHERE id=?',[cuentaPagoRollback.id]))[0][0].saldo_pendiente),3);
  const cancelKey='venta-cancelacion-rollback';r=await request('/ventas/crear',{method:'POST',headers:{'Idempotency-Key':cancelKey},body:{cliente_id:clienteId,tipo_pago:'CONTADO',metodo_pago:'EFECTIVO',idempotency_key:cancelKey,productos:[{producto_id:productoRollback.insertId,cantidad:1,precio_unitario:10}]}});assert.equal(r.status,201);const ventaCancelRollback=r.data.venta_id;
  const stockAntesCancelar=Number((await db.promise.query('SELECT stock FROM productos WHERE id=?',[productoRollback.insertId]))[0][0].stock);
  await db.promise.query("CREATE TRIGGER test_fallo_cancelacion BEFORE UPDATE ON ventas FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='Fallo cancelacion inducido'");
  r=await request(`/ventas/${ventaCancelRollback}/cancelar`,{method:'POST',body:{motivo:'Fallo controlado de cancelación',password_admin:password}});assert.equal(r.status,500);
  await db.promise.query('DROP TRIGGER test_fallo_cancelacion');
  assert.equal((await db.promise.query('SELECT estado_venta FROM ventas WHERE id=?',[ventaCancelRollback]))[0][0].estado_venta,'ACTIVA');
  assert.equal(Number((await db.promise.query('SELECT stock FROM productos WHERE id=?',[productoRollback.insertId]))[0][0].stock),stockAntesCancelar);
  const statsAntesMedianoche=await request('/stats');
  const[[calendario]]=await db.promise.query("SELECT DATE_FORMAT(CURDATE(),'%Y-%m-%d') hoy,@@session.time_zone zona");
  const[vHoy]=await db.promise.query("INSERT INTO ventas(cliente_id,fecha,total,tipo_pago,estado_pago,usuario_id,estado_venta,idempotency_key) VALUES(?,CONCAT(CURDATE(),' 00:00:01'),10,'CREDITO','PENDIENTE',?,'ACTIVA','fecha-hoy-0001')",[clienteId,onlyAdmin.id]);
  await db.promise.query('INSERT INTO detalle_venta(venta_id,producto_id,cantidad,precio_unitario,subtotal) VALUES(?,?,1,10,10)',[vHoy.insertId,productoRollback.insertId]);
  const[vAyer]=await db.promise.query("INSERT INTO ventas(cliente_id,fecha,total,tipo_pago,estado_pago,usuario_id,estado_venta,idempotency_key) VALUES(?,DATE_SUB(CONCAT(CURDATE(),' 00:00:00'),INTERVAL 1 SECOND),10,'CREDITO','PENDIENTE',?,'ACTIVA','fecha-ayer-235959')",[clienteId,onlyAdmin.id]);
  await db.promise.query('INSERT INTO detalle_venta(venta_id,producto_id,cantidad,precio_unitario,subtotal) VALUES(?,?,1,10,10)',[vAyer.insertId,productoRollback.insertId]);
  const statsDespuesMedianoche=await request('/stats');assert.equal(Number(statsDespuesMedianoche.data.ventas_hoy),Number(statsAntesMedianoche.data.ventas_hoy)+1);
  r=await request(`/ventas?fecha_inicio=${calendario.hoy}&fecha_fin=${calendario.hoy}`);assert.equal(r.status,200);assert.ok(r.data.some(x=>x.id===vHoy.insertId));assert.ok(!r.data.some(x=>x.id===vAyer.insertId));
  const backupId='11111111-2222-4333-8444-555555555555';const[[admin]]=await db.promise.query("SELECT id FROM usuarios WHERE username='admin_test'");await db.promise.query("INSERT INTO historial_traslados(backup_id,equipo_origen,generado_por,estado) VALUES(?,?,?,'GENERADO')",[backupId,require('os').hostname(),admin.id]);
  r=await request('/backups/mark-transferred',{method:'POST',body:{backupId,password_admin:password}});assert.equal(r.status,200);
  r=await request('/clientes',{method:'POST',body:{nombre_razon_social:'Debe bloquearse'}});assert.equal(r.status,423);
  r=await request('/clientes');assert.equal(r.status,200);
  r=await request('/backups/reactivate',{method:'POST',body:{motivo:'Reactivación de integración',password_admin:password}});assert.equal(r.status,200);
  r=await request('/clientes',{method:'POST',body:{nombre_razon_social:'Escritura reactivada'}});assert.equal(r.status,201);
  token=null;for(let i=0;i<10;i++){r=await request('/auth/login',{method:'POST',body:{username:'usuario_inexistente',password:'incorrecta'}});assert.equal(r.status,401);}
  await new Promise(resolve=>server.close(resolve));await new Promise(resolve=>{server=app.listen(0,'127.0.0.1',resolve)});base=`http://127.0.0.1:${server.address().port}`;
  r=await request('/auth/login',{method:'POST',body:{username:'usuario_inexistente',password:'incorrecta'}});assert.equal(r.status,429);
  r=await request('/auth/login',{method:'POST',body:{username:'otro_usuario',password:'incorrecta'}});assert.equal(r.status,401);
});
