const express=require('express');const db=require('../db/conexion');const{permitirRoles}=require('../middleware/auth');const router=express.Router();
router.use(permitirRoles('ADMON_GRAL'));
const data=b=>({nombre:String(b.nombre||'').trim(),contacto:String(b.contacto||'').trim()||null,telefono:String(b.telefono||'').trim()||null,correo:String(b.correo||'').trim().toLowerCase()||null,direccion:String(b.direccion||'').trim()||null,rfc:String(b.rfc||'').trim().toUpperCase()||null,notas:String(b.notas||'').trim()||null});
router.get('/',async(req,res,next)=>{try{const q=String(req.query.buscar||'').trim(),todos=req.query.incluir_inactivos==='1';const[r]=await db.promise.query(`SELECT * FROM proveedores WHERE (?=1 OR activo=1) AND (?='' OR nombre LIKE ? OR rfc LIKE ? OR telefono LIKE ?) ORDER BY activo DESC,nombre`,[todos?1:0,q,`%${q}%`,`%${q}%`,`%${q}%`]);res.json(r);}catch(e){next(e);}});
router.get('/:id',async(req,res,next)=>{try{const[[proveedor],[compras]]=await Promise.all([db.promise.query('SELECT * FROM proveedores WHERE id=?',[req.params.id]),db.promise.query('SELECT id,folio,total,estado,fecha FROM compras WHERE proveedor_id=? ORDER BY fecha DESC,id DESC LIMIT 100',[req.params.id])]);if(!proveedor[0])return res.status(404).json({error:'Proveedor no encontrado'});res.json({proveedor:proveedor[0],compras});}catch(e){next(e);}});
router.post('/',async(req,res,next)=>{const p=data(req.body);if(!p.nombre)return res.status(400).json({error:'Nombre obligatorio'});try{const[r]=await db.promise.query('INSERT INTO proveedores (nombre,contacto,telefono,correo,direccion,rfc,notas) VALUES (?,?,?,?,?,?,?)',Object.values(p));res.status(201).json({id:r.insertId,mensaje:'Proveedor creado'});}catch(e){if(e.code==='ER_DUP_ENTRY')return res.status(409).json({error:'El RFC ya existe'});next(e);}});
router.put('/:id',async(req,res,next)=>{const p=data(req.body);if(!p.nombre)return res.status(400).json({error:'Nombre obligatorio'});try{const[r]=await db.promise.query('UPDATE proveedores SET nombre=?,contacto=?,telefono=?,correo=?,direccion=?,rfc=?,notas=? WHERE id=?',[...Object.values(p),req.params.id]);if(!r.affectedRows)return res.status(404).json({error:'Proveedor no encontrado'});res.json({mensaje:'Proveedor actualizado'});}catch(e){if(e.code==='ER_DUP_ENTRY')return res.status(409).json({error:'El RFC ya existe'});next(e);}});
router.patch('/:id/estado',async(req,res,next)=>{try{const activo=req.body.activo===true||req.body.activo===1,[r]=await db.promise.query('UPDATE proveedores SET activo=? WHERE id=?',[activo?1:0,req.params.id]);if(!r.affectedRows)return res.status(404).json({error:'Proveedor no encontrado'});res.json({mensaje:activo?'Proveedor activado':'Proveedor desactivado'});}catch(e){next(e);}});
module.exports=router;
