$ErrorActionPreference='Stop';$root=(Resolve-Path (Join-Path $PSScriptRoot '..')).Path;$stage=Join-Path $root 'dist\POS-Aguacates-iPhone-Preview-1.0.1';if(Test-Path $stage){throw 'La variante iPhone Preview 1.0.1 ya existe; no se reemplazó ni eliminó nada.'}
New-Item -ItemType Directory -Force -Path "$stage\app","$stage\runtime","$stage\service"|Out-Null
Copy-Item "$root\pos-frontend" "$stage\app\pos-frontend" -Recurse;Copy-Item "$root\pos-backend" "$stage\app\pos-backend" -Recurse -Exclude '.env','node_modules','logs','data','temp','backups'
$backend="$stage\app\pos-backend";@('backups','logs','data','temp','test','integration-tests')|ForEach-Object{$p=Join-Path $backend $_;if(Test-Path $p){[IO.Directory]::Delete($p,$true)}};Get-ChildItem "$stage\app" -Recurse -File|Where-Object{$_.Extension -in @('.bak','.backup','.log','.zip')}|Remove-Item -Force
Copy-Item "$root\mobile-preview\mobile.css" "$stage\app\pos-frontend\css\mobile.css";Copy-Item "$root\mobile-preview\mobile.js" "$stage\app\pos-frontend\js\mobile.js";Copy-Item "$root\mobile-preview\manifest.webmanifest" "$stage\app\pos-frontend\manifest.webmanifest"
$html="$stage\app\pos-frontend\index.html";$text=Get-Content $html -Raw -Encoding UTF8;$text=$text.Replace('<meta name="viewport" content="width=device-width,initial-scale=1">','<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#416b57"><meta name="apple-mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-status-bar-style" content="default"><link rel="manifest" href="/manifest.webmanifest">').Replace('<link rel="stylesheet" href="./css/styles.css">','<link rel="stylesheet" href="./css/styles.css"><link rel="stylesheet" href="./css/mobile.css">').Replace('</body>','<script src="./js/mobile.js"></script></body>');Set-Content $html $text -Encoding UTF8
$config="$backend\scripts\configurarEmpresa.js";$text=Get-Content $config -Raw -Encoding UTF8;$text=$text.Replace('`PORT=3000`','`PORT=3001`').Replace('`HOST=127.0.0.1`','`HOST=0.0.0.0`').Replace('CORS_ORIGINS=http://localhost:3000,http://127.0.0.1:3000','CORS_ORIGINS=http://localhost:3001,http://127.0.0.1:3001');Set-Content $config $text -Encoding UTF8
$index="$backend\index.js";$text=Get-Content $index -Raw -Encoding UTF8;$needle='if (!origin || allowedOrigins.includes(origin)) return callback(null, true);';$replacement="if (!origin || allowedOrigins.includes(origin)) return callback(null, true);`r`n    try { const u=new URL(origin); if (u.port===String(process.env.PORT||3000) && /^(?:192\.168\.|10\.|172\.(?:1[6-9]|2\d|3[01])\.)/.test(u.hostname)) return callback(null,true); } catch {}";$text=$text.Replace($needle,$replacement);Set-Content $index $text -Encoding UTF8
Push-Location $backend;try{npm.cmd ci --omit=dev --ignore-scripts}finally{Pop-Location};Copy-Item (Get-Command node.exe).Source "$stage\runtime\node.exe";Copy-Item "$root\packaging\vendor\WinSW-x64.exe" "$stage\service\POSAguacates.exe";Copy-Item "$root\packaging\POSAguacates.xml" "$stage\service\POSAguacates.xml";Copy-Item "$root\packaging\instalar-mobile.ps1" "$stage\instalar.ps1"
$serviceXml="$stage\service\POSAguacates.xml";$xml=Get-Content $serviceXml -Raw -Encoding UTF8;$xml=$xml.Replace('<id>POSAguacates</id>','<id>POSAguacatesMobilePreview</id>').Replace('<name>POS Aguacates</name>','<name>POS Aguacates iPhone Preview</name>');Set-Content $serviceXml $xml -Encoding UTF8
$bad=Get-ChildItem $stage -Recurse -File|Where-Object{$_.FullName -notmatch '\\node_modules\\' -and ($_.Name -eq '.env' -or $_.FullName -match '\\(backups|logs|data|temp|test|integration-tests)\\' -or $_.Extension -in @('.bak','.backup','.log','.zip'))};if($bad){throw "Artefactos prohibidos: $($bad.FullName -join ', ')"};Get-ChildItem $stage -Recurse -File|Get-FileHash -Algorithm SHA256|ForEach-Object{"$($_.Hash)  $($_.Path.Substring($stage.Length+1))"}|Set-Content "$stage\SHA256SUMS.txt";Write-Host "Variante creada en $stage"
